displayName=Confirm Spellbook
author=Endrit
description=Confirm your spellbook when carrying a thrall book or rune pouch, and check for missing thrall supplies
tags=endrit,confirm,ancients,standard,lunar,arceuus,thrall,thralls,book of the dead,spell,spellbook,reminder,necromancy,resurrect,ghost,skeleton,zombie,rune,runes,lesser,superior,greater,casts,air,earth,fire,mind,death,blood,cosmic,staff,tome,rune pouch
plugins=com.bookofthedeadnotifier.BookOfTheDeadNotifierPlugin
build=standard
